### ISSUE TITLE
Consider refactoring your CSS classes to using the BEM naming system

### ISSUE THREAD

**Issue by nickcannariato** [KBiz65/kevinbisner-com#16]
This is absolutely not necessary, but something I want you to consider. 

As I'm sure you've noticed by now, writing HTML and CSS can be a bit daunting. you have to write _hundreds_ of lines of HTML and CSS to build anything interesting, and deciding what to name things is, as always, a problem.

If you're anything like me, you constantly find yourself asking things like "what the fuck should I name _this_ class? Should I just use the HTML selector? Do I really _need_ a class?"

If that's you, then this might help. There's a CSS naming system called BEM, which is short for Block Element Modifier.
http://getbem.com/

It's not a new type of CSS, think of it more like a writing style guide. It just tells you how to _think_ about naming things, and specific formats to name things. 

I (and many many others) find that it makes it much easier to think about how to style my application.

I'll let you read up on it, but the way it helps is by providing some rules, for example: everything gets a class and you only write CSS rules for classes.

From there, it gives you a way of _thinking_ about the stuff on your site.  It has you break things into blocks, elements, and then tells you to optionally add modifiers, and then gives you a way of writing those that makes sense. Let's use your code as an example.

### Converting to BEM: Blog List

We're going to apply BEM to your Post list in your blog template (and also learn some shortcuts you may have missed at the same time 😉).

Currently, the for loop that you use to print your posts in your template looks like this:

https://github.com/KBiz65/kevinbisner-com/blob/1b2a309fc8a6dca644c57f808006b477a85ff546/blog/templates/blogs/blog_detail_view.html#L14-L22

Let's take everything we've learned so far and clean this up before adding BEM. First, we'll fix some structure and names:

```django
<!-- I changed it from "for id in posts" to "for post in posts" because it's more readable and also it makes it easier to reason about inside the for loop (e.g. you're typing {{ post.title }} instead of {{ id.title }} -->
{% for post in posts %}

<!-- I switched this div to an `article` tag, mostly because whenever possible, you should try to use semantic HTML (meaning, HTML that tells the computer what it is, see references below) -->
<!-- I also switched some of your p tags to h2s and h3s, also for semantics -->
<article class="blogs-posted">
  <h2 class="blog-title">{{ post.title }}</p>

  <!-- Note: this exercise also assumes you've made the changes I detailed in my other issues, so if you haven't read those yet you'll want to start at the beginning, otherwise post.author and post.published_at won't work -->
   <h3 class="blog-tagline">Created by: {{ post.author }} on {{ post.published_at }}</p>
   <p class="blog-text">{{ post.text }}</p>
</article>

<!-- I moved the hr tag outside of the div above since it doesn't "belong" to the post, and should therefore be outside of it -->
<hr />
{% endfor %}
```

Ok, that's a little better already. Naming the object we're looping through helps. Also, as a compliment to you, you're already _mostly_ writing BEM code, you're just thinking about the site as a whole and not the individual pieces of it.

If we look at just this loop, we see that it's iterating over a list of posts and rendering one post at a time onto the page. With that in mind, we can assume that all of the HTML inside of this loop has to do with displaying a post object, yeah?. So let's edit the class names to reflect that.

```django
{% for post in posts %}
<!-- I changed this class from "blogs-posted" to "post", since that's the object (or "block" as BEM calls it) that we're working with -->
<article class="post">
  
  <!-- Similarly, I changed this class to "post-title", since that's the *element* of the post "block" that it represents -->
  <h2 class="post-title">{{ post.title }}</p>
  
  <!--This one is changed from "blog-tagline" to "post-meta" because it's not really a tagline of the post, it's information *about* the post -->
  <h3 class="post-meta">Created by: {{ post.author }} on {{ post.published_at }}</p>
  
  <!-- This one I changed from "blog-text" to "post-summary", because it's going to contain the first 100 words of the post, and nothing else -->
  <!-- BONUS KNOWLEDGE: the " | truncatewords: 100" is known as a Filter in django. I'm telling the template that I only want up to 100 words of however long post.text is -->
  <p class="post-summary">{{ post.text | truncatewords: 100 }}</p>
  
<!-- Below is a bit of magic, but it's the "right" way to get a URL to a specific Post (or any other object in Django) -->
  <!-- This assumes that your app's view is named "blog" and your post_detail view is named "detail", it also assumes that the ID is what your URL needs to find a post -->
  <a href="{% url "blog:detail" post.id %}" class="post-link" />
</article>

<!-- Added a class to this since it's definitely _an_ element of the Post object, but not _part_ of the Post itself -->
<hr class="post-separator" />
{% endfor %}
```

That's _much_ better, now every part of the Post block has a class, and each class is intuitively named.

One major additional benefit of writing CSS this way is that you can move all your CSS into one file, instead of the two or three files you're currently using.

The reason that works is because we're only targeting classes now, so there are no conflicts with styles like there would be if we were just using `header` or `p` tags as our CSS selectors.

That means we can change our CSS to look like this:

```css
/*
* POST
* 
* Styles for the blog.models.Post object.
*/
.post {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: auto;
    background-color: white;
}

.post-title {
    display: flex;
    justify-content: center;
    margin-top: 1rem;
    margin-bottom: 0;
    width: 75%;
    height: auto; 
    font-family: Volkorn, serif;
    font-size: 3rem;
    color: navy;
}

.post-meta {
    display: flex;
    justify-content: center;
    width: 100%;
    height: auto;
    font-family: Yantramanav, sans-serif;
    font-size: 1.25rem;
}

.post-summary {
    display: flex;
    align-items: center;
    justify-content: flex-start;
    width: 80%;
    height: auto;
    font-family: Yantramanav, sans-serif;
    font-size: 2rem;
}

.post-separator {
    border: 1px dashed black;
    width: 50%;  
}
```

Isn't that easier to read and understand?
